name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.09.25'

      - name: Clojure version
        run: clojure --version

      - name: Run clj-kondo
        run: clj-kondo --lint src

      - name: Use oxr463/setup-leiningen
        uses: oxr463/setup-leiningen@0.0.1
        with:
          exec: lein uberjar
